\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={KNN Blood},
            pdfauthor={Dominika SkĂłrska \& Zuzanna Zajkowska},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{KNN Blood}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Dominika SkĂłrska \& Zuzanna Zajkowska}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{21 maja 2019}


\begin{document}
\maketitle

\subsection{Zastosowanie metody k-najbliższych sąsiadów do klasyfikacji
dawców krwi.
(R)}\label{zastosowanie-metody-k-najblizszych-sasiadow-do-klasyfikacji-dawcow-krwi.-r}

Zastosowane metody klasyfikacji k-najbliższych sąsiadów do przewidzenia
czy osoba odda krew w marcu czy nie, na podstawie pozostałych
parametrów.

Dane: \textbf{Zmienne}:

Recency - czas od ostatniego oddania krwi (w miesiącach)

Frequency - częstość (ile razy ogólnie oddano krew)

Monetary - ile w sumie oddano krwi w cm3

Time - czas od pierwszego oddania krwi (w miesiącach)

Whether he/she donated blood in March - zmienna prognozowana: czy dawca
odda krew w Marcu

Celem projektu jest zbudowanie zbioru treningowego i testowego,
zbudowania modelu w celu zbadania trafności algorytmu KNN dla
prognozowania tego czy dawca odda krew w danym miesiącu na bazie
wymienionych wyżej zmiennych.

\subsection{Metoda k-najbliższych
sąsiadów}\label{metoda-k-najblizszych-sasiadow}

\textbf{Opis metody:} Założenia: Dany jest zbiór uczący. Każdy przypadek
w tym zbiorze zawiera wektor niezależnych zmiennych i wartość zmiennej
zależnej Y. Dany jest przypadek C zawierający wektor zmiennych
niezależnych. Dla tego przypadku chcemy prognozować wartość zmiennej
zależnej Y

\textbf{Algorytm: }

Porównanie niezależnych zmiennych przypadku C z wartościami tych
zmiennych dla każdego przypadku ze zbioru treningowego.

Wybór k (wcześniej określona liczba) najbliższych do C przypadków ze
zbioru treningowego.

Definicja prognozy

Średnia wartość zmiennych zależnych dla wybranych obserwacji w przypadku
problemu regresyjnego

Przydział najczęściej pojawiającej się klasy spośród wybranych
obserwacji w przypadku problemu klasyfikacji

Algorytm K - najbliższych sąsiadów jest szczególnie użyteczny, kiedy
zależność pomiędzy zmiennymi zależnymi a niezależnymi jest skomplikowana
lub nietypowa (np. niemonotoniczna), tzn. trudna do modelowania w
klasyczny sposób. W przypadku gdy ta zależność jest łatwa do
interpretacji (np. liniowa), i zbiór nie zawiera wartości odstających,
klasyczne metody (np. regresja liniowa) dają zazwyczaj lepsze rezultaty.

\subsection{Podział na zbiór uczący i
testowy}\label{podzia-na-zbior-uczacy-i-testowy}

Dane zostały podzielone w stosunku 7:3 na zbiór uczący i testowy.
Algorytm dopasuje model do zbioru uczącego i na tej podstawie możliwe
będzie wykonanie prognozy dla zbioru testowego i porównnie wyników z
rzeczywistymi wartościami.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{101}\NormalTok{)}
\NormalTok{split <-}\StringTok{ }\KeywordTok{sample.split}\NormalTok{(dane_final}\OperatorTok{$}\NormalTok{donated, }\DataTypeTok{SplitRatio =} \FloatTok{0.70}\NormalTok{)}
\NormalTok{train <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(dane_final, split }\OperatorTok{==}\StringTok{ }\OtherTok{TRUE}\NormalTok{)}
\NormalTok{test <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(dane_final, split }\OperatorTok{==}\StringTok{ }\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{\texorpdfstring{Wybór liczby
``k''}{Wybór liczby k}}\label{wybor-liczby-k}

W celu wyboru optymalnej liczby ``k'' (najbliższyszch sąsiadóW) należy
narysować odpowiedni wykres. Wykres przedstawia liczbę najbliższych
sąsiadów (oś X) oraz dokładność (oś Y), obliczoną na podstawie
sprawdzianu krzyżowego. Liczbie ``k'' odpowiada moment na wywkresie w
którym wartość funkcji stabilizuje się.

Innym spoosbem na wyznaczenie liczby ``k'' jest obliczenie pierwiastka z
liczby wszystkich obserwacji.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{400}\NormalTok{)}
\NormalTok{ctrl <-}\StringTok{ }\KeywordTok{trainControl}\NormalTok{(}\DataTypeTok{method =} \StringTok{"repeatedcv"}\NormalTok{, }\DataTypeTok{repeats =} \DecValTok{3}\NormalTok{)}
\NormalTok{knnFit <-}\StringTok{ }\KeywordTok{train}\NormalTok{(donated }\OperatorTok{~}\StringTok{ }\NormalTok{., }\DataTypeTok{data =}\NormalTok{ train, }\DataTypeTok{method =} \StringTok{"knn"}\NormalTok{, }\DataTypeTok{trControl =}\NormalTok{ ctrl, }\DataTypeTok{preProcess =} \KeywordTok{c}\NormalTok{(}\StringTok{"center"}\NormalTok{,}\StringTok{"scale"}\NormalTok{),}\DataTypeTok{tuneLength =} \DecValTok{10}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(knnFit)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{nrow}\NormalTok{(train))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 22.89105
\end{verbatim}

Na podstawie wykresu liczbę ``k'' ustalono na 21, a na podstawie
obliczenia pierwiastka ``k'' = 22. Zostaną porównane wyniki dla obydwóch
wartości.

\subsection{Budowa modelu, prognoza i określenie
trafności}\label{budowa-modelu-prognoza-i-okreslenie-trafnosci}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{101}\NormalTok{)}
\NormalTok{predicted_}\DecValTok{21}\NormalTok{ <-}\StringTok{ }\KeywordTok{knn}\NormalTok{(train[}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{], test[}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{], train}\OperatorTok{$}\NormalTok{donated, }\DataTypeTok{k =} \DecValTok{21}\NormalTok{)}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{101}\NormalTok{)}
\NormalTok{predicted_}\DecValTok{22}\NormalTok{ <-}\StringTok{ }\KeywordTok{knn}\NormalTok{(train[}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{], test[}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{], train}\OperatorTok{$}\NormalTok{donated, }\DataTypeTok{k =} \DecValTok{22}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Przedstawienie wyników: }\label{przedstawienie-wynikow}

Na podstawie parametrów: recency, fequency, monetary, time zbudowany
został model przewidujący czy dany dawca odda krew w najbliższym
miesiącu. Wynik przyjmuje postać liczby binarnej, dla której ``1''
oznacza oddanie krwi, a ``0'' nie.

Wyniki zbadano dla 2 opcji: k=21 oraz k=22.

\textbf{k = 21}

Confusion matrix and rates:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{conf_matrix21 <-}\StringTok{ }\KeywordTok{table}\NormalTok{(predicted_}\DecValTok{21}\NormalTok{, test}\OperatorTok{$}\NormalTok{donated)}
\NormalTok{msl_rate_}\DecValTok{21}\NormalTok{ <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(test}\OperatorTok{$}\NormalTok{donated }\OperatorTok{!=}\StringTok{ }\NormalTok{predicted_}\DecValTok{21}\NormalTok{)}
\NormalTok{accuracy_}\DecValTok{21}\NormalTok{ <-}\StringTok{ }\NormalTok{(conf_matrix21[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{conf_matrix21[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{nrow}\NormalTok{(test)}
\NormalTok{conf_matrix21}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             
## predicted_21   0   1
##            0 167  48
##            1   4   5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{msl_rate_}\DecValTok{21}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2321429
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_}\DecValTok{21}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7678571
\end{verbatim}

167 przypadków zostało dobrze sklasyfikowanych jako ``0'' oraz 5 dobrze
sklasyfikowanych jako ``1''. 48 przypadków zostało błędnie
sklasyfikowanych jako ``1'' i 4 przypadki błędnie sklasyfikowane jako
``0''.

Błędnie sklasyfikowano 23,2\% przypadków ze zbioru testowego.

Poprawnie sklasyfikowano 76,8\% przypadków ze zbioru testowego.

\textbf{k = 22}

Confusion matrix and rates:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{conf_matrix22 <-}\StringTok{ }\KeywordTok{table}\NormalTok{(predicted_}\DecValTok{22}\NormalTok{, test}\OperatorTok{$}\NormalTok{donated)}
\NormalTok{msl_rate_}\DecValTok{22}\NormalTok{ <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(test}\OperatorTok{$}\NormalTok{donated }\OperatorTok{!=}\StringTok{ }\NormalTok{predicted_}\DecValTok{22}\NormalTok{)}
\NormalTok{accuracy_}\DecValTok{22}\NormalTok{ <-}\StringTok{ }\NormalTok{(conf_matrix22[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{conf_matrix22[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{nrow}\NormalTok{(test)}
\NormalTok{conf_matrix22}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             
## predicted_22   0   1
##            0 164  47
##            1   7   6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{msl_rate_}\DecValTok{22}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2410714
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_}\DecValTok{22}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7589286
\end{verbatim}

164 przypadków zostało dobrze sklasyfikowanych jako ``0'' oraz 6 dobrze
sklasyfikowanych jako ``1''. 47 przypadków zostało błędnie
sklasyfikowanych jako ``1'' i 7 przypadki błędnie sklasyfikowane jako
``0''.

Błędnie sklasyfikowano 24,1\% przypadków ze zbioru testowego.

Poprawnie sklasyfikowano 75,9\% przypadków ze zbioru testowego.

\textbf{Minimalnie lepsze wyniki daje zastosowanie algorytmu dla k = 21,
dla którego jesteśmy w stanie oszacować wyniki z prawdopodobieństwem na
poziomie 76,8\%.}


\end{document}
